/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "oqazxfewxttctehgftuy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xYXp4ZmV3eHR0Y3RlaGdmdHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MTA1MzMsImV4cCI6MjA3NTQ4NjUzM30.clEAcNfxWcWg-bKHhas9pMm2d5Lj8b5-qRHjzMCs1tY"